name:                simple-grin
version:             0.1.0
github:              "fizruk/simple-grin"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2022 Nickolay Kudasov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/simple-grin#readme>

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- array
- mtl

library:
  source-dirs: src
  when:
  - condition: false
    other-modules:
    - Syntax.Fun.Test
    - Syntax.Lambda.Test
    - Syntax.LambdaNameless.Test
    - Syntax.GRIN.Test

executables:
  haskell-codeworld-template:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-grin

