{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Syntax.
--   Generated by the BNF converter.

module Syntax.Lambda.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Syntax.Lambda.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.Lambda.Abs.Con where
  prt _ (Syntax.Lambda.Abs.Con i) = doc $ showString i

instance Print Syntax.Lambda.Abs.Var where
  prt _ (Syntax.Lambda.Abs.Var i) = doc $ showString i
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Syntax.Lambda.Abs.Var] where
  prt = prtList

instance Print Syntax.Lambda.Abs.Program where
  prt i = \case
    Syntax.Lambda.Abs.Program bindings -> prPrec i 0 (concatD [prt 0 bindings])

instance Print Syntax.Lambda.Abs.Binding where
  prt i = \case
    Syntax.Lambda.Abs.Binding var vars exp -> prPrec i 0 (concatD [prt 0 var, prt 0 vars, doc (showString "="), prt 0 exp])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Syntax.Lambda.Abs.Binding] where
  prt = prtList

instance Print Syntax.Lambda.Abs.Exp where
  prt i = \case
    Syntax.Lambda.Abs.Case exp caseexps -> prPrec i 0 (concatD [doc (showString "case"), prt 1 exp, doc (showString "of"), doc (showString "{"), prt 0 caseexps, doc (showString "}")])
    Syntax.Lambda.Abs.Let var exp1 exp2 -> prPrec i 0 (concatD [doc (showString "let"), prt 0 var, doc (showString "="), prt 1 exp1, doc (showString "in"), prt 0 exp2])
    Syntax.Lambda.Abs.LetS var exp1 exp2 -> prPrec i 0 (concatD [doc (showString "letS"), prt 0 var, doc (showString "="), prt 1 exp1, doc (showString "in"), prt 0 exp2])
    Syntax.Lambda.Abs.Constructor con atoms -> prPrec i 1 (concatD [prt 0 con, prt 0 atoms])
    Syntax.Lambda.Abs.App var atoms -> prPrec i 1 (concatD [prt 0 var, prt 0 atoms])
    Syntax.Lambda.Abs.Atom atom -> prPrec i 2 (concatD [prt 0 atom])

instance Print Syntax.Lambda.Abs.CaseExp where
  prt i = \case
    Syntax.Lambda.Abs.CaseExp pat exp -> prPrec i 0 (concatD [prt 0 pat, doc (showString "->"), prt 0 exp])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Syntax.Lambda.Abs.CaseExp] where
  prt = prtList

instance Print Syntax.Lambda.Abs.Atom where
  prt i = \case
    Syntax.Lambda.Abs.AtomVar var -> prPrec i 0 (concatD [prt 0 var])
    Syntax.Lambda.Abs.AtomLiteral literal -> prPrec i 0 (concatD [prt 0 literal])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Syntax.Lambda.Abs.Atom] where
  prt = prtList

instance Print Syntax.Lambda.Abs.Literal where
  prt i = \case
    Syntax.Lambda.Abs.LitInteger n -> prPrec i 0 (concatD [prt 0 n])

instance Print Syntax.Lambda.Abs.Pat where
  prt i = \case
    Syntax.Lambda.Abs.ConPat con vars -> prPrec i 0 (concatD [prt 0 con, prt 0 vars])
    Syntax.Lambda.Abs.LitPat literal -> prPrec i 0 (concatD [prt 0 literal])

