{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Syntax.
--   Generated by the BNF converter.

module Syntax.GRIN.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Syntax.GRIN.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.GRIN.Abs.Tag where
  prt _ (Syntax.GRIN.Abs.Tag i) = doc $ showString i

instance Print Syntax.GRIN.Abs.Var where
  prt _ (Syntax.GRIN.Abs.Var i) = doc $ showString i
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Syntax.GRIN.Abs.Program where
  prt i = \case
    Syntax.GRIN.Abs.Program bindings -> prPrec i 0 (concatD [prt 0 bindings])

instance Print Syntax.GRIN.Abs.Binding where
  prt i = \case
    Syntax.GRIN.Abs.Binding var vars exp -> prPrec i 0 (concatD [prt 0 var, prt 0 vars, doc (showString "="), doc (showString "{"), prt 0 exp, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Syntax.GRIN.Abs.Binding] where
  prt = prtList

instance Print [Syntax.GRIN.Abs.Var] where
  prt = prtList

instance Print Syntax.GRIN.Abs.Exp where
  prt i = \case
    Syntax.GRIN.Abs.Sequencing exp1 lpat exp2 -> prPrec i 0 (concatD [prt 1 exp1, doc (showString "$"), doc (showString "\955"), prt 0 lpat, doc (showString "\8594"), doc (showString ";"), prt 0 exp2])
    Syntax.GRIN.Abs.Case val caseexps -> prPrec i 0 (concatD [doc (showString "case"), prt 0 val, doc (showString "of"), doc (showString "{"), prt 0 caseexps, doc (showString "}")])
    Syntax.GRIN.Abs.App var simplevals -> prPrec i 1 (concatD [prt 0 var, prt 0 simplevals])
    Syntax.GRIN.Abs.Unit val -> prPrec i 1 (concatD [doc (showString "unit"), prt 0 val])
    Syntax.GRIN.Abs.Store val -> prPrec i 1 (concatD [doc (showString "store"), prt 0 val])
    Syntax.GRIN.Abs.Fetch var -> prPrec i 1 (concatD [doc (showString "fetch"), prt 0 var])
    Syntax.GRIN.Abs.Update var val -> prPrec i 1 (concatD [doc (showString "update"), prt 0 var, prt 0 val])

instance Print Syntax.GRIN.Abs.CaseExp where
  prt i = \case
    Syntax.GRIN.Abs.CaseExp cpat exp -> prPrec i 0 (concatD [prt 0 cpat, doc (showString "\8594"), doc (showString "{"), prt 0 exp, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [Syntax.GRIN.Abs.CaseExp] where
  prt = prtList

instance Print Syntax.GRIN.Abs.SimpleVal where
  prt i = \case
    Syntax.GRIN.Abs.SimpleLiteral literal -> prPrec i 0 (concatD [prt 0 literal])
    Syntax.GRIN.Abs.SimpleVar var -> prPrec i 0 (concatD [prt 0 var])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Syntax.GRIN.Abs.SimpleVal] where
  prt = prtList

instance Print Syntax.GRIN.Abs.Val where
  prt i = \case
    Syntax.GRIN.Abs.ConstantTag tag simplevals -> prPrec i 0 (concatD [doc (showString "("), prt 0 tag, prt 0 simplevals, doc (showString ")")])
    Syntax.GRIN.Abs.VariableTag var simplevals -> prPrec i 0 (concatD [doc (showString "("), prt 0 var, prt 0 simplevals, doc (showString ")")])
    Syntax.GRIN.Abs.SingleTag tag -> prPrec i 0 (concatD [prt 0 tag])
    Syntax.GRIN.Abs.Empty -> prPrec i 0 (concatD [doc (showString "()")])
    Syntax.GRIN.Abs.SimpleVal simpleval -> prPrec i 0 (concatD [prt 0 simpleval])

instance Print Syntax.GRIN.Abs.LPat where
  prt i = \case
    Syntax.GRIN.Abs.LPat val -> prPrec i 0 (concatD [prt 0 val])

instance Print Syntax.GRIN.Abs.CPat where
  prt i = \case
    Syntax.GRIN.Abs.ConstNodePattern tag vars -> prPrec i 0 (concatD [doc (showString "("), prt 0 tag, prt 0 vars, doc (showString ")")])
    Syntax.GRIN.Abs.ConstTagPattern tag -> prPrec i 0 (concatD [prt 0 tag])
    Syntax.GRIN.Abs.ConstLiteral literal -> prPrec i 0 (concatD [prt 0 literal])

instance Print Syntax.GRIN.Abs.Literal where
  prt i = \case
    Syntax.GRIN.Abs.LitInteger n -> prPrec i 0 (concatD [prt 0 n])
    Syntax.GRIN.Abs.LitBoolFalse -> prPrec i 0 (concatD [doc (showString "False")])
    Syntax.GRIN.Abs.LitBoolTrue -> prPrec i 0 (concatD [doc (showString "True")])

